#ifndef PQMAGIC_AIGIS_PROVIDER_H
#define PQMAGIC_AIGIS_PROVIDER_H

#include <stdint.h>
#include "crypt_eal_implprovider.h"
#include "pqmagic_api.h"

#ifdef __cplusplus
extern "C" {
#endif

#define PQMAGIC_AIGIS_PROVIDER_NAME "provider=pqmagic-aigis"

#define PQMAGIC_PKEY_AIGIS_SIG1 0x89000001
#define PQMAGIC_PKEY_AIGIS_SIG2 0x89000002
#define PQMAGIC_PKEY_AIGIS_SIG3 0x89000003

#define PQMAGIC_AIGIS_PARAM_BASE 5200
#define PQMAGIC_AIGIS_PARAM_PUBKEY (PQMAGIC_AIGIS_PARAM_BASE + 1)
#define PQMAGIC_AIGIS_PARAM_PRVKEY (PQMAGIC_AIGIS_PARAM_BASE + 2)

#define PQMAGIC_AIGIS_SIG1_PUBLICKEYBYTES AIGIS_SIG1_PUBLICKEYBYTES
#define PQMAGIC_AIGIS_SIG1_SECRETKEYBYTES AIGIS_SIG1_SECRETKEYBYTES
#define PQMAGIC_AIGIS_SIG1_SIGBYTES AIGIS_SIG1_SIGBYTES

#define PQMAGIC_AIGIS_SIG2_PUBLICKEYBYTES AIGIS_SIG2_PUBLICKEYBYTES
#define PQMAGIC_AIGIS_SIG2_SECRETKEYBYTES AIGIS_SIG2_SECRETKEYBYTES
#define PQMAGIC_AIGIS_SIG2_SIGBYTES AIGIS_SIG2_SIGBYTES

#define PQMAGIC_AIGIS_SIG3_PUBLICKEYBYTES AIGIS_SIG3_PUBLICKEYBYTES
#define PQMAGIC_AIGIS_SIG3_SECRETKEYBYTES AIGIS_SIG3_SECRETKEYBYTES
#define PQMAGIC_AIGIS_SIG3_SIGBYTES AIGIS_SIG3_SIGBYTES

#define PQMAGIC_AIGIS_SUCCESS 0
#define PQMAGIC_AIGIS_ERR_NULL_INPUT (-1)
#define PQMAGIC_AIGIS_ERR_NOT_SUPPORT (-2)
#define PQMAGIC_AIGIS_ERR_ALLOC_FAIL (-3)
#define PQMAGIC_AIGIS_ERR_INVALID_ARG (-4)
#define PQMAGIC_AIGIS_ERR_BUFFER_TOO_SMALL (-5)
#define PQMAGIC_AIGIS_ERR_KEY_NOT_SET (-6)
#define PQMAGIC_AIGIS_ERR_VERIFY_FAIL (-7)

int32_t PQMagic_AIGIS_ProviderInit(CRYPT_EAL_ProvMgrCtx *mgrCtx, BSL_Param *param,
    CRYPT_EAL_Func *capFuncs, CRYPT_EAL_Func **outFuncs, void **provCtx);

#ifdef __cplusplus
}
#endif

#endif

